### ISSUE TITLE
Test/adjust for dark theme

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/imagingdatacommons.github.io#3]
As suggested in #2 by @s-paquette,

> we might want to adjust this because if someone is using a dark theme a transparent favicon may not look so great -- I'll look at some options eg. with a pale drop-shadow/glow which would disappear on a light theme and let it show up on a dark one, and you can see if you'd prefer that. (Or I can just put them on a white background, of course.)

**Comment by fedorov** [comment]
As aside, I am using dark theme on Android (Pixel 3a) and on macOS, and it looks just fine to me. No pressure/high priority to look into this, but if this is something you know how to quickly test, please go ahead!

**Comment by notZaki** [comment]
There was some [recent activity on stackoverflow](https://stackoverflow.com/questions/55170708/detect-if-the-browser-is-using-dark-mode-and-use-a-different-favicon) for accommodating dark themes which might be useful.

An alternative could be to change the colour---the darkest one specifically---to something more neutral that can show up on both light and dark backgrounds.
[Here's a preview](https://notzaki.github.io/imagingdatacommons.github.io/) of what that would look like, with the [source images available here](https://github.com/notZaki/imagingdatacommons.github.io/tree/gh-pages/assets/img)

**Comment by fedorov** [comment]
Thank you for investigating this - the proposed approach is fine with me! @s-paquette let us know your thoughts.

**Comment by s-paquette** [comment]
@notZaki That looks great, and was what I was thinking as well--just replace the darker color on the top with a lighter one. I can swap those out unless you wanted to in a quick PR.

**Comment by notZaki** [comment]
For completeness, here is a version with a [white background](https://idc-pr.netlify.com/), but I think it makes the favicon feel constricted.

If the version with the darker colour replaced with the grey looks good then I'll open a PR.

**Comment by s-paquette** [comment]
Yeah I didn't like my white background results either, I think that works alright with the sorts of super simple favicons (the single letter ones, that kind of thing) but for this the transparent image looks better.

**Comment by notZaki** [comment]
I opened a PR with the updated icons.
[Here's an SVG version just in case](https://gist.github.com/notZaki/9c3c854fa4f8c1126ed6e6973a9117fa)

**Comment by fedorov** [comment]
Resolved by #4. Thank you @notZaki!
